#!/bin/bash

#
#
#    ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ 
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░   
#     ░            ░               ░           ░   
#          ░                                       
#

# #######################################################################
# #                             FUNCTIONS                               #
# #######################################################################

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# #######################################################################
# #                            AUTOSTART                                #
# #######################################################################

# BINDINGS
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap se &
ksuperkey &

# CURSOR FIX
xsetroot -cursor_name left_ptr &

# DISABLE CSD IN GTK
gsettings set org.gnome.desktop.wm.preferences button-layout ""

# COMPOSITOR
picom &

# BAR
$HOME/.config/polybar/launch.sh &

# NOTIFICATION DAEMON
dunst &

# PLAYERCTL SUPPORT FOR MPD
mpDris2 &

# POLKIT
[ -n "$(pidof polkit-gnome-authentication-agent-1)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# WALLPAPER
$HOME/.fehbg &

# PULL APPS REQUIRING ATTENTION INTO FOCUS
$HOME/.config/bspwm/scripts/bspfocus &

# #######################################################################
# #                               RULES                                 #
# ####################################################################### 

rule Alacritty                       state=floating
rule kitty                           state=floating
rule mpv                             state=floating
rule Zathura                         state=floating
rule Thunar                          state=floating
rule bpytop                          state=floating
rule Signal                          state=floating
rule btm                             state=floating
rule Gpick                           state=floating
rule Lxappearance                    state=floating 
rule feh                             state=floating
rule Genymotion                      state=floating
rule obsidian                        desktop=^1
rule librewolf                       desktop=^1  
rule Lutris                          desktop=^2 state=floating
rule 'riotclientux.exe'              desktop=^2 state=floating
rule 'league of legends.exe'         desktop=^2 state=fullscreen
rule 'leagueclientux.exe'            desktop=^2 state=floating  
rule 'Genymotion Player'             desktop=^2 state=floating
rule 'Genymotion'                    desktop=^2 state=floating
rule 'Jellyfin Media Player'         desktop=^5
config external_rules_command "$HOME/.config/bspwm/scripts/spotifyrule.sh"

# #######################################################################
# #                           GENERAL CONFIG                            #
# #######################################################################

bspc monitor -d 1 2 3 4 5 

config border_width            6
config window_gap              10
config split_ratio             0.50

config borderless_monocle      true
config gapless_monocle         true 
config top_padding             10
config bottom_padding          10
config left_padding            10
config right_padding           10
config focus_follows_pointer   true

config pointer_modifier        Mod4
config pointer_action1         move
config pointer_action2         resize_side
config pointer_action2         resize_corner

config focused_border_color    "#0A0D0F"
config normal_border_color     "#0A0D0F"
config active_border_color     "#0A0D0F"

start borders
